runtime: nodejs20
instance_class: F1
automatic_scaling:
  min_instances: 0

handlers:
# Handler for CV
- url: /Clement_Ou_resume\.pdf
  static_files: static/Clement_Ou_resume.pdf
  upload: static/Clement_Ou_resume\.pdf
  secure: always
  redirect_http_response_code: 301

# Handler for font files
- url: /assets/(.*\.ttf)$
  static_files: dist/assets/\1
  upload: dist/assets/(.*\.ttf)$
  secure: always
  redirect_http_response_code: 301

# Handler for other static files
- url: /(.*\.(gif|png|jpg|css|js))$
  static_files: dist/\1
  upload: dist/(.*\.(gif|png|jpg|css|js))$
  secure: always
  redirect_http_response_code: 301

# Handler for HTML
- url: /.*
  static_files: dist/index.html
  upload: dist/index.html
  secure: always
  redirect_http_response_code: 301
